name: Get PR Number

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - qa

jobs:
    get-pr-number:
        runs-on: ubuntu-latest
        steps:
            - name: Get PR Number
              id: get_pr_number
              run: echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

            - name: Run getJobID shell script
              run: |
                ./getJobID.sh "${{ env.pr_number }}"