name: getSFDeploymentID

on:
  repository_dispatch:
    types: [run_my_bat]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Deployment ID
        run: |
            #echo "SF ID Displayed"
            echo "Deployment ID: ${{github.event.client_payload.SALESFORCE_DEPLOYMENT_ID}}"