name: getSFDeploymentID

on:
  repository_dispatch:
    types: [run_my_bat]
  workflow_dispatch:


jobs:
  GetSFDeploymentId:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Deployment ID
        run: |
            echo "Deployment ID: ${{github.event.client_payload.SALESFORCE_DEPLOYMENT_ID}}"
  CallDisplaySFDeploymentId:
    needs: GetSFDeploymentId
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Call DisplaySFDeploymentId workflow
        uses: ./.github/workflows/displaySFDeploymentId.yml
        with:
          SALESFORCE_DEPLOYMENT_ID: ${{github.event.client_payload.SALESFORCE_DEPLOYMENT_ID}}