name: getSFDeploymentID

on:
  repository_dispatch:
    types: [run_my_bat]
  workflow_dispatch:


jobs:
  GetSFDeploymentId:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Deployment ID
        run: |
            echo "Deployment ID: ${{github.event.client_payload.DeploymentID}}"
            echo "VCS URL: ${{github.event.client_payload.VCSURL}}"
  CallDisplaySFDeploymentId:
    needs: GetSFDeploymentId
    uses: Somanath-Inc/l2c-test/.github/workflows/displaySFDeploymentID.yml@main
    with:
      deployment_id: ${{github.event.client_payload.DeploymentID}}