name: getSFDeploymentID

on:
  repository_dispatch:
    types: [run_my_bat]
  workflow_dispatch:


jobs:
  GetSFDeploymentId:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Deployment ID
        run: |
            echo "Deployment ID: ${{github.event.client_payload.SALESFORCE_DEPLOYMENT_ID}}"
  CallDisplaySFDeploymentId:
    needs: GetSFDeploymentId
    uses: Somanath-Inc/l2c-test/.github/workflows/displaySFDeploymentId.yml@main
    with:
      SALESFORCE_DEPLOYMENT_ID: ${{github.event.client_payload.SALESFORCE_DEPLOYMENT_ID}}