name: getSFDeploymentID

on:
  repository_dispatch:
    types: [run_my_bat]
  workflow_dispatch:

jobs:
  GetSFDeploymentId:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Display Deployment ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            DeploymentID=${{github.event.client_payload.DeploymentID}}
            deploymentId=$(echo $DeploymentID | cut -c 1-15)
            echo "VCS URL: ${{github.event.client_payload.VCSURL}}"
            CommitID=${{github.event.client_payload.commitId}}
            PULLS_URL="https://api.github.com/repos/Somanath-Inc/l2c-test/commits/$CommitID/pulls"
            AUTH_HEADER="Authorization: Bearer {{ secrets.GITHUB_TOKEN }}"
            PULLS_RESPONSE=$(curl --request GET \
            --url "$PULLS_URL" --ssl-no-revoke \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: $AUTH_HEADER ")
            prNum=$(echo $PULLS_RESPONSE | jq -r '.[] | .number')
            gh pr comment $prNum --body "Deployment ID: $deploymentId
                                         URL: [Validation Errors]("https://java-saas-7806--qa.sandbox.my.salesforce-setup.com/lightning/setup/DeployStatus/page?address=%2Fchangemgmt%2FmonitorDeploymentsDetails.apexp%3FasyncId%3D$deploymentId%26retURL%3D%252Fchangemgmt%252FmonitorDeployment.apexp")"